blueprint:
  name: "Automatizacion Alarma"
  description: "Hace sonar una alarma si uno o varios sensores han detectado movimiento durante un tiempo determinado y se desactiva si no detecta movimiento. Envía una notificación a los teléfonos configurados."
  domain: automation
  input:
    motion_sensors:
      name: "Sensores de movimiento"
      description: "Selecciona uno o varios sensores de movimiento."
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    alarm:
      name: "Dispositivo de alarma"
      description: "Selecciona el dispositivo de alarma a activar."
      selector:
        entity:
          domain: siren

    delay_time:
      name: "Tiempo de espera (minutos)"
      description: "Tiempo que debe permanecer activo el sensor antes de activar la alarma."
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutos"
          mode: slider

    off_delay_time:
      name: "Tiempo de espera para apagado (minutos)"
      description: "Tiempo que debe permanecer sin detección de movimiento antes de desactivar la alarma."
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutos"
          mode: slider

    notify_devices:
      name: "Dispositivos para notificación"
      description: "Selecciona los dispositivos que recibirán notificaciones."
      selector:
        device:
          filter:
            integration: mobile_app


mode: restart

trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"
    for:
      minutes: !input delay_time
    id: "movimiento_detectado"

  - platform: state
    entity_id: !input motion_sensors
    to: "off"
    for:
      minutes: !input off_delay_time
    id: "movimiento_terminado"

action:
  - variables:
      dispositivos_notificacion: >-
        {{ expand(!input notify_devices) | map(attribute='entity_id') | map('device_id') | map('device_attr', 'name') | map('slugify') | list }}

  - choose:
      - conditions:
          - condition: trigger
            id: "movimiento_detectado"
        sequence:
          - service: siren.turn_on
            target:
              entity_id: !input alarm
          - repeat:
              for_each: "{{ dispositivos_notificacion }}"
              sequence:
                - service: "notify.mobile_app_{{ repeat.item }}"
                  data:
                    title: "⚠️ Alerta de Movimiento"
                    message: "Se ha detectado movimiento continuo."
                    data:
                      push:
                        interruption-level: time-sensitive

      - conditions:
          - condition: trigger
            id: "movimiento_terminado"
        sequence:
          - service: siren.turn_off
            target:
              entity_id: !input alarm
          - repeat:
              for_each: "{{ dispositivos_notificacion }}"
              sequence:
                - service: "notify.mobile_app_{{ repeat.item }}"
                  data:
                    title: "✅ Alarma Desactivada"
                    message: "No se detecta más movimiento."
                    data:
                      push:
                        interruption-level: passive
