blueprint:
  name: Control inteligente de calefacción
  description: >
    Enciende la calefacción cuando hay presencia durante un tiempo determinado y la temperatura está por debajo del valor del termostato. Apaga la calefacción cuando no hay presencia durante el mismo tiempo o la temperatura supera el valor del termostato.
  domain: automation
  input:
    termostato_activado:
      name: Termostato activado
      selector:
        entity:
          domain: input_boolean

    temperatura_actual:
      name: Sensor de temperatura
      selector:
        entity:
          domain: sensor

    temperatura_objetivo:
      name: Temperatura objetivo
      selector:
        entity:
          domain: input_number

    escena_encendido:
      name: Escena de encendido de calefacción
      selector:
        entity:
          domain: scene

    escena_apagado:
      name: Escena de apagado de calefacción
      selector:
        entity:
          domain: scene

    sensores_presencia:
      name: Sensores de presencia
      selector:
        entity:
          multiple: true
          domain: binary_sensor

    tiempo_presencia:
      name: Tiempo de presencia requerido (minutos)
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min

mode: single

trigger:
  - platform: state
    entity_id: !input sensores_presencia
    to: 'on'
    for:
      minutes: !input tiempo_presencia
  - platform: numeric_state
    entity_id: !input temperatura_actual
    below: !input temperatura_objetivo
    for:
      minutes: !input tiempo_presencia
  - platform: state
    entity_id: !input sensores_presencia
    to: 'off'
    for:
      minutes: !input tiempo_presencia
  - platform: numeric_state
    entity_id: !input temperatura_actual
    above: !input temperatura_objetivo

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input termostato_activado
            state: 'on'
          - condition: numeric_state
            entity_id: !input temperatura_actual
            below: !input temperatura_objetivo
          - condition: or
            conditions:
              - condition: state
                entity_id: !input sensores_presencia
                state: 'on'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input escena_encendido

      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input sensores_presencia
                state: 'off'
                for:
                  minutes: !input tiempo_presencia
              - condition: numeric_state
                entity_id: !input temperatura_actual
                above: !input temperatura_objetivo
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input escena_apagado
