blueprint:
  name: "Escena Condicional con Input Booleano"
  description: "Activa una de dos escenas en función del estado de un input booleano."
  domain: automation
  input:
    toggle_boolean:
      name: "Interruptor de condición"
      description: "Selecciona la entidad booleana que determinará qué acción se activa."
      selector:
        entity:
          filter:
            - domain: input_boolean
            - domain: switch
            - domain: binary_sensor
    scene_true:
      name: "Acción cuando es True"
      description: "Escena, script o entidad que se encenderá cuando el booleano esté en 'on'."
      selector:
        entity:
          filter:
            - domain: scene
            - domain: script
            - domain: input_boolean
            - domain: switch
    scene_false:
      name: "Acción cuando es False"
      description: "Escena, script o entidad que se apagará cuando el booleano esté en 'off'."
      selector:
        entity:
          filter:
            - domain: scene
            - domain: script
            - domain: input_boolean
            - domain: switch
    toggle_entities:
      name: "Dispositivos a controlar"
      description: "Entidades que se encenderán con 'on' y se apagarán con 'off'."
      default: []
      selector:
        entity:
          multiple: true
    delay_seconds:
      name: "Retraso en segundos"
      description: "Tiempo a esperar antes de ejecutar la acción."
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: segundos
          mode: box

mode: restart

trigger:
  - platform: state
    entity_id: !input toggle_boolean

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input toggle_boolean
            state: "on"
        sequence:
          - delay: !input delay_seconds
          - service: homeassistant.turn_on
            target:
              entity_id: !input scene_true
          - service: homeassistant.turn_on
            target:
              entity_id: !input toggle_entities
      - conditions:
          - condition: state
            entity_id: !input toggle_boolean
            state: "off"
        sequence:
          - delay: !input delay_seconds
          - service: homeassistant.turn_on
            target:
              entity_id: !input scene_false
          - service: homeassistant.turn_off
            target:
              entity_id: !input toggle_entities
