blueprint:
  name: Control de climatizacion por presencia
  description: >
    Automatiza calefaccion y enfriador segun un rango de temperatura cuando se detecta presencia.
  domain: automation
  input:
    sensor_temperatura:
      name: Sensor de temperatura
      selector:
        entity:
          domain: sensor
          device_class: temperature
    calefaccion:
      name: Calefaccion
      description: Entidad a activar para calentar
      selector:
        entity:
          filter:
            - domain: switch
            - domain: input_boolean
    enfriador:
      name: Enfriador
      description: Entidad a activar para enfriar
      selector:
        entity:
          filter:
            - domain: switch
            - domain: input_boolean
    temperatura_minima:
      name: Temperatura minima
      selector:
        entity:
          domain: input_number
    temperatura_maxima:
      name: Temperatura maxima
      selector:
        entity:
          domain: input_number
    sensores_presencia:
      name: Sensores de presencia
      description: Sensores o grupos que indican si hay alguien presente.
      selector:
        entity:
          filter:
            - domain: binary_sensor
          multiple: true
    tiempo_ausencia:
      name: Tiempo sin presencia
      description: Minutos a esperar sin presencia antes de apagar el clima.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutos"

mode: restart

trigger:
  - platform: state
    entity_id: !input sensor_temperatura
  - platform: state
    entity_id: !input sensores_presencia
    to: "on"
  - platform: state
    entity_id: !input sensores_presencia
    to: "off"
    for:
      minutes: !input tiempo_ausencia

variables:
  calefaccion_entity: !input calefaccion
  enfriador_entity: !input enfriador
  calefaccion_domain: "{{ calefaccion_entity.split('.')[0] }}"
  enfriador_domain: "{{ enfriador_entity.split('.')[0] }}"
  sensores_presencia_var: !input sensores_presencia

condition: []

action:
  - variables:
      hay_presencia: >
        {{ sensores_presencia_var | select('is_state', 'on') | list | count > 0 }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ hay_presencia }}"
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input sensor_temperatura
                    above: !input temperatura_maxima
                  - condition: template
                    value_template: "{{ is_state(enfriador_entity, 'off') }}"
                sequence:
                  - service: "{{ enfriador_domain }}.turn_on"
                    target:
                      entity_id: "{{ enfriador_entity }}"
              - conditions:
                  - condition: numeric_state
                    entity_id: !input sensor_temperatura
                    below: !input temperatura_minima
                  - condition: template
                    value_template: "{{ is_state(enfriador_entity, 'on') }}"
                sequence:
                  - service: "{{ enfriador_domain }}.turn_off"
                    target:
                      entity_id: "{{ enfriador_entity }}"
            default: []
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input sensor_temperatura
                    below: !input temperatura_minima
                  - condition: template
                    value_template: "{{ is_state(calefaccion_entity, 'off') }}"
                sequence:
                  - service: "{{ calefaccion_domain }}.turn_on"
                    target:
                      entity_id: "{{ calefaccion_entity }}"
              - conditions:
                  - condition: numeric_state
                    entity_id: !input sensor_temperatura
                    above: !input temperatura_maxima
                  - condition: template
                    value_template: "{{ is_state(calefaccion_entity, 'on') }}"
                sequence:
                  - service: "{{ calefaccion_domain }}.turn_off"
                    target:
                      entity_id: "{{ calefaccion_entity }}"
            default: []
      - conditions:
          - condition: template
            value_template: "{{ not hay_presencia }}"
        sequence:
          - service: "{{ enfriador_domain }}.turn_off"
            target:
              entity_id: "{{ enfriador_entity }}"
          - service: "{{ calefaccion_domain }}.turn_off"
            target:
              entity_id: "{{ calefaccion_entity }}"
    default: []
