blueprint:
  name: Control de climatizacion por presencia u horario
  description: >
    Automatiza calefacción y enfriador según un rango de temperatura cuando se detecta presencia
    o dentro de un horario configurado.
  domain: automation
  input:
    sensor_temperatura:
      name: Sensor de temperatura
      selector:
        entity:
          domain: sensor
          device_class: temperature
    calefaccion:
      name: Calefaccion
      description: Entidad a activar para calentar
      selector:
        entity:
          filter:
            - domain: switch
            - domain: input_boolean
    enfriador:
      name: Enfriador
      description: Entidad a activar para enfriar
      selector:
        entity:
          filter:
            - domain: switch
            - domain: input_boolean
    temperatura_minima:
      name: Temperatura minima
      selector:
        entity:
          domain: input_number
    temperatura_maxima:
      name: Temperatura maxima
      selector:
        entity:
          domain: input_number
    diferencia_activacion:
      name: Diferencia de activacion
      description: Diferencia en °C para anticipar la activación respecto a los límites mínimos y máximos.
      default: 0
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: "°C"
    sensores_presencia:
      name: Sensores de presencia
      description: Sensores o grupos que indican si hay alguien presente.
      selector:
        entity:
          filter:
            - domain: binary_sensor
          multiple: true
    tiempo_ausencia:
      name: Tiempo sin presencia
      description: Minutos a esperar sin presencia antes de apagar el clima.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutos"
    controlar_por_presencia:
      name: Controlar por presencia
      description: Activa el control cuando se detecta presencia.
      default: true
      selector:
        boolean: {}
    controlar_por_horario:
      name: Controlar por horario
      description: Activa el control dentro de un rango horario.
      default: false
      selector:
        boolean: {}
    hora_inicio:
      name: Hora de inicio
      description: Inicio del rango horario.
      default: "08:00:00"
      selector:
        time: {}
    hora_fin:
      name: Hora de fin
      description: Fin del rango horario.
      default: "18:00:00"
      selector:
        time: {}
    retardo_accion:
      name: Retardo antes de actuar
      description: Tiempo en segundos a esperar antes de encender o apagar la climatización.
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: "segundos"

mode: restart

trigger:
  - platform: state
    entity_id: !input sensor_temperatura
  - platform: state
    entity_id: !input sensores_presencia
    to: "on"
  - platform: state
    entity_id: !input sensores_presencia
    to: "off"
    for:
      minutes: !input tiempo_ausencia
  - platform: time
    at: !input hora_inicio
  - platform: time
    at: !input hora_fin
  - platform: time_pattern
    minutes: "/5"

variables:
  sensor_temperatura_var: !input sensor_temperatura
  temperatura_minima_var: "{{ states(!input temperatura_minima) | float(0) }}"
  temperatura_maxima_var: "{{ states(!input temperatura_maxima) | float(0) }}"
  diferencia_activacion_var: !input diferencia_activacion
  temperatura_minima_activacion: "{{ (temperatura_minima_var | float(0)) + (diferencia_activacion_var | float(0)) }}"
  temperatura_maxima_activacion: "{{ (temperatura_maxima_var | float(0)) - (diferencia_activacion_var | float(0)) }}"
  retardo_accion_var: !input retardo_accion
  temperatura_actual: "{{ states(sensor_temperatura_var) | float(0) }}"
  calefaccion_entity: !input calefaccion
  enfriador_entity: !input enfriador
  calefaccion_domain: "{{ calefaccion_entity.split('.')[0] }}"
  enfriador_domain: "{{ enfriador_entity.split('.')[0] }}"
  sensores_presencia_var: !input sensores_presencia
  controlar_por_presencia_var: !input controlar_por_presencia
  controlar_por_horario_var: !input controlar_por_horario
  hora_inicio_var: !input hora_inicio
  hora_fin_var: !input hora_fin

condition: []

action:
  - variables:
      hay_presencia: >
        {{ sensores_presencia_var | select('is_state', 'on') | list | count > 0 }}
      dentro_horario: >
        {% set inicio = hora_inicio_var %}
        {% set fin = hora_fin_var %}
        {% set ahora = now().strftime('%H:%M:%S') %}
        {% if inicio <= fin %}
          {{ ahora >= inicio and ahora <= fin }}
        {% else %}
          {{ ahora >= inicio or ahora <= fin }}
        {% endif %}
      control_activo: >
        {{ (controlar_por_presencia_var and hay_presencia) or (controlar_por_horario_var and dentro_horario) }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ control_activo }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ temperatura_actual >= temperatura_maxima_activacion }}
                sequence:
                  - delay: "{{ retardo_accion_var | int(0) }}"
                  - service: "{{ enfriador_domain }}.turn_on"
                    target:
                      entity_id: "{{ enfriador_entity }}"
            default:
              - delay: "{{ retardo_accion_var | int(0) }}"
              - service: "{{ enfriador_domain }}.turn_off"
                target:
                  entity_id: "{{ enfriador_entity }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ temperatura_actual <= temperatura_minima_activacion }}
                sequence:
                  - delay: "{{ retardo_accion_var | int(0) }}"
                  - service: "{{ calefaccion_domain }}.turn_on"
                    target:
                      entity_id: "{{ calefaccion_entity }}"
            default:
              - delay: "{{ retardo_accion_var | int(0) }}"
              - service: "{{ calefaccion_domain }}.turn_off"
                target:
                  entity_id: "{{ calefaccion_entity }}"
        - conditions:
            - condition: template
              value_template: "{{ not control_activo }}"
          sequence:
            - delay: "{{ retardo_accion_var | int(0) }}"
            - service: "{{ enfriador_domain }}.turn_off"
              target:
                entity_id: "{{ enfriador_entity }}"
            - service: "{{ calefaccion_domain }}.turn_off"
              target:
              entity_id: "{{ calefaccion_entity }}"
    default: []
