blueprint:
  name: Control de Deshumidificador Automático
  description: Enciende o apaga un deshumidificador según los valores de humedad y una lógica activadora.
  domain: automation
  input:
    deshumidificacion_activada:
      name: Input Boolean - Deshumidificación Activada (Control)
      selector:
        entity:
          domain: input_boolean
    deshumidificador:
      name: Input Boolean - Deshumidificador (Dispositivo)
      selector:
        entity:
          domain: input_boolean
    sensor_humedad:
      name: Sensor de Humedad
      selector:
        entity:
          domain: sensor
          device_class: humidity
    humedad_maxima:
      name: Humedad Máxima Permitida
      selector:
        entity:
          domain: input_number
    humedad_minima:
      name: Humedad Mínima Permitida
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input sensor_humedad

condition:
  - condition: state
    entity_id: !input deshumidificacion_activada
    state: "on"

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_humedad
            above: !input humedad_maxima
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input deshumidificador
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_humedad
            below: !input humedad_minima
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input deshumidificador

mode: single
