blueprint:
  name: "Control de luces por sensores de presencia y puertas"
  description: "Enciende luces si algún sensor de presencia está ocupado. Apaga las luces tras un tiempo sin detección. También enciende luces si una puerta se abre y no hay presencia."
  domain: automation
  input:
    sensores_presencia:
      name: Sensores de presencia
      description: "Selecciona los sensores de presencia a monitorear."
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    luces:
      name: Luces
      description: "Selecciona las luces que se encenderán y apagarán automáticamente."
      selector:
        entity:
          domain: light
          multiple: true

    sensores_puerta:
      name: Sensores de puerta
      description: "Selecciona los sensores de puerta que activarán las luces."
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    tiempo_apagado:
      name: Tiempo de apagado
      description: "Tiempo en minutos antes de apagar las luces si no hay presencia. Si es 0, se apagarán inmediatamente."
      default: 1
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutos"

    solo_noche:
      name: "Solo encender después de la puesta del sol"
      description: "Si está activado, las luces solo se encenderán después de la puesta del sol."
      default: false
      selector:
        boolean:

mode: restart

trigger:
  - platform: state
    entity_id: !input sensores_presencia
    to: "on"
    id: "presencia_detectada"

  - platform: state
    entity_id: !input sensores_presencia
    to: "off"
    for:
      minutes: !input tiempo_apagado
    id: "sin_presencia"

  - platform: state
    entity_id: !input sensores_puerta
    to: "on"
    id: "puerta_abierta"

condition: []

action:
  - variables:
      solo_noche_var: !input solo_noche

  - choose:
      - conditions:
          - condition: trigger
            id: "presencia_detectada"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ not solo_noche_var }}"
              - condition: sun
                after: sunset
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input luces

      - conditions:
          - condition: trigger
            id: "sin_presencia"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input luces

      - conditions:
          - condition: trigger
            id: "puerta_abierta"
          - condition: state
            entity_id: !input sensores_presencia
            state: "off"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ not solo_noche_var }}"
              - condition: sun
                after: sunset
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input luces
