blueprint:
  name: "Control de luces de Habitación"
  description: "Enciende luces si una puerta se abre y no hay presencia, siempre que la iluminación ambiental sea insuficiente o no haya sensor de luz. Apaga las luces cuando no haya presencia. También permite alternar las luces mediante un botón Zigbee o interruptor."
  domain: automation
  input:
    sensores_presencia:
      name: Sensores de presencia
      description: "Selecciona los sensores de presencia o grupos de sensores a monitorear."
      selector:
        entity:
          filter:
            - domain: binary_sensor
          multiple: true

    luces:
      name: Luces
      description: "Selecciona las luces que se encenderán y apagarán automáticamente."
      default: []
      selector:
        entity:
          domain: light
          multiple: true

    sensores_puerta:
      name: Sensores de puerta
      description: "Selecciona los sensores de puerta o grupos que activarán las luces."
      selector:
        entity:
          filter:
            - domain: binary_sensor
            - domain: group
          multiple: true

    sensores_luz:
      name: Sensores de luz (opcional)
      description: "Selecciona los sensores de luz que determinarán si la iluminación ambiental es insuficiente."
      default: []
      selector:
        entity:
          domain: sensor
          device_class: illuminance
          multiple: true

    umbral_luz:
      name: Umbral de luz
      description: "Nivel de iluminación (en lux) por debajo del cual las luces se encenderán automáticamente."
      default: 5000
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: "lux"

    tiempo_apagado:
      name: Tiempo de apagado
      description: "Tiempo en minutos antes de apagar las luces si no hay presencia."
      default: 1
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutos"

    interruptor_estado:
      name: Interruptores o botones
      description: "Selecciona interruptores, sensores o botones Zigbee (ZHA) que activan el control manual."
      default: []
      selector:
        device:
          multiple: true

mode: restart

trigger:
  - platform: state
    entity_id: !input sensores_puerta
    to: "on"
    id: "puerta_abierta"

  - platform: state
    entity_id: !input sensores_presencia
    to: "off"
    for:
      minutes: !input tiempo_apagado
    id: "sin_presencia"

  - platform: event
    event_type: zha_event
    id: "interruptor_manual"

condition: []

action:
  - variables:
      sensores_luz_var: !input sensores_luz
      umbral_luz_var: !input umbral_luz
      sensores_presencia_var: !input sensores_presencia
      luces_var: !input luces
      interruptores_var: !input interruptor_estado
      click_type: "{{ trigger.event.data.command if trigger.event.data is defined else '' }}"

  - choose:
      - conditions:
          - condition: trigger
            id: "puerta_abierta"
          - condition: state
            entity_id: !input sensores_presencia
            state: "off"
          - condition: template
            value_template: >
              {{ sensores_luz_var | count == 0 or
                 (sensores_luz_var | map('states', 0) | map('float', 0) | min < umbral_luz_var) }}
          - condition: template
            value_template: "{{ luces_var | count > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input luces

      - conditions:
          - condition: trigger
            id: "sin_presencia"
          - condition: template
            value_template: >
              {{ expand(sensores_presencia_var) | selectattr('state', 'eq', 'off') | list | count == expand(sensores_presencia_var) | list | count }}
          - condition: template
            value_template: "{{ luces_var | count > 0 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input luces

      - conditions:
          - condition: trigger
            id: "interruptor_manual"
          - condition: template
            value_template: >
              {{ luces_var | count > 0 and
                 (interruptores_var | count == 0 or
                  trigger.event.data.device_id in interruptores_var) and
                 click_type in ['single', 'double'] }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ click_type == 'single' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input luces

              - conditions:
                  - condition: template
                    value_template: "{{ click_type == 'double' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input luces
