blueprint:
  name: "Control de luces por sensores"
  description: "Enciende luces si algún sensor de presencia está ocupado. Apaga las luces tras un tiempo sin detección. También enciende luces si una puerta se abre y no hay presencia. Además, se activan si la iluminación ambiental es insuficiente."
  domain: automation
  input:
    sensores_presencia:
      name: Sensores de presencia
      description: "Selecciona los sensores de presencia o grupos de sensores a monitorear."
      selector:
        entity:
          filter:
            - domain: binary_sensor
          multiple: true

    luces:
      name: Luces
      description: "Selecciona las luces que se encenderán y apagarán automáticamente."
      selector:
        entity:
          domain: light
          multiple: true

    sensores_puerta:
      name: Sensores de puerta (opcional)
      description: "Selecciona los sensores de puerta o grupos que activarán las luces."
      default: []
      selector:
        entity:
          filter:
            - domain: binary_sensor
          multiple: true

    sensores_luz:
      name: Sensores de luz (opcional)
      description: "Selecciona los sensores de luz que determinarán si la iluminación ambiental es insuficiente."
      default: []
      selector:
        entity:
          domain: sensor
          device_class: illuminance
          multiple: true

    umbral_luz:
      name: Umbral de luz (opcional)
      description: "Nivel de iluminación (en lux) por debajo del cual las luces se encenderán automáticamente."
      default: 5000
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: "lux"

    tiempo_apagado:
      name: Tiempo de apagado
      description: "Tiempo en minutos antes de apagar las luces si no hay presencia. Si es 0, se apagarán inmediatamente."
      default: 1
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutos"

mode: restart

trigger:
  - platform: state
    entity_id: !input sensores_presencia
    to: "on"
    id: "presencia_detectada"

  - platform: state
    entity_id: !input sensores_presencia
    to: "off"
    for:
      minutes: !input tiempo_apagado
    id: "sin_presencia"

  - platform: state
    entity_id: !input sensores_puerta
    to: "on"
    id: "puerta_abierta"

condition: []

action:
  - variables:
      sensores_presencia_var: !input sensores_presencia
      sensores_luz_var: !input sensores_luz
      sensores_puerta_var: !input sensores_puerta
      umbral_luz_var: !input umbral_luz

  - choose:
      - conditions:
          - condition: trigger
            id: "presencia_detectada"
          - condition: template
            value_template: >
              {{ sensores_luz_var | count == 0 or
                 (sensores_luz_var | map('states', 0) | map('float', 0) | min < umbral_luz_var) }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input luces

      - conditions:
          - condition: trigger
            id: "sin_presencia"
          - condition: template
            value_template: >
              {{ sensores_presencia_var | map('states') | select('eq', 'off') | list | count == sensores_presencia_var | count }}
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input luces

      - conditions:
          - condition: trigger
            id: "puerta_abierta"
          - condition: state
            entity_id: !input sensores_presencia
            state: "off"
          - condition: template
            value_template: >
              {{ sensores_luz_var | count == 0 or
                 (sensores_luz_var | map('states', 0) | map('float', 0) | min < umbral_luz_var) }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input luces
