blueprint:
  name: "Timbre inteligente por planta"
  description: >
    Suena un timbre y ejecuta un script según qué sensor (por planta) detecte presencia.
    Si ningún sensor detecta, se activa un Fingerbot como fallback.
  domain: automation

  input:
    sensores:
      name: "Sensores de presencia por planta"
      description: "Ordenados por planta. Si hay movimiento, se activará el timbre correspondiente y se ejecutará un script con él como parámetro."
      selector:
        entity:
          filter:
            - domain: binary_sensor
          multiple: true

    timbres:
      name: "Timbres por planta"
      description: "Lista de dispositivos de timbre, debe coincidir el orden con los sensores."
      selector:
        entity:
          domain: siren
          multiple: true

    script:
      name: "Script a ejecutar"
      description: "Script que se ejecutará con el timbre como parámetro."
      selector:
        entity:
          domain: script

    fingerbot:
      name: "Fingerbot de respaldo"
      description: "Dispositivo que se activará si ningún sensor detecta movimiento."
      selector:
        entity:
          domain: switch

    boton:
      name: "Botón de activación del timbre"
      description: "Botón que activa la lógica de timbre."
      selector:
        entity:
          domain: input_button

mode: queued

trigger:
  - platform: state
    entity_id: !input boton
    to: "on"

variables:
  sensores_var: !input sensores
  timbres_var: !input timbres
  script_var: !input script
  fingerbot_var: !input fingerbot

action:
  - variables:
      activados: >-
        {% set lista = [] %}
        {% for i in range(sensores_var | length) %}
          {% if is_state(sensores_var[i], 'on') %}
            {% set _ = lista.append(i) %}
          {% endif %}
        {% endfor %}
        {{ lista }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ activados | length > 0 }}"
        sequence:
          - repeat:
              for_each: "{{ activados }}"
              sequence:
                - service: script.turn_on
                  target:
                    entity_id: "{{ script_var }}"
                  data:
                    variables:
                      sirena: "{{ timbres_var[repeat.item] }}"
      - conditions:
          - condition: template
            value_template: "{{ activados | length == 0 }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ fingerbot_var }}"
